# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\klacourse\Documents\NGosselin\gitRepos\ceamscarms\Stand_alone_apps\scinodes_poc\src\main\python\plugins\EdfXmlWriter\Ui_EdfXmlWriterResultsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_EdfXmlWriterResultsView(object):
    def setupUi(self, EdfXmlWriterResultsView):
        EdfXmlWriterResultsView.setObjectName("EdfXmlWriterResultsView")
        EdfXmlWriterResultsView.resize(483, 360)
        self.verticalLayout = QtWidgets.QVBoxLayout(EdfXmlWriterResultsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.result_layout = QtWidgets.QVBoxLayout()
        self.result_layout.setObjectName("result_layout")
        self.verticalLayout.addLayout(self.result_layout)

        self.retranslateUi(EdfXmlWriterResultsView)
        QtCore.QMetaObject.connectSlotsByName(EdfXmlWriterResultsView)

    def retranslateUi(self, EdfXmlWriterResultsView):
        _translate = QtCore.QCoreApplication.translate
        EdfXmlWriterResultsView.setWindowTitle(_translate("EdfXmlWriterResultsView", "Form"))
