# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\klacourse\Documents\NGosselin\gitRepos\ceamscarms\Stand_alone_apps\snooz-toolbox\src\main\python\plugins\StringManip\Ui_StringManipResultsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_StringManipResultsView(object):
    def setupUi(self, StringManipResultsView):
        StringManipResultsView.setObjectName("StringManipResultsView")
        StringManipResultsView.resize(927, 262)
        self.verticalLayout = QtWidgets.QVBoxLayout(StringManipResultsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.signal_layout = QtWidgets.QVBoxLayout()
        self.signal_layout.setObjectName("signal_layout")
        self.verticalLayout.addLayout(self.signal_layout)

        self.retranslateUi(StringManipResultsView)
        QtCore.QMetaObject.connectSlotsByName(StringManipResultsView)

    def retranslateUi(self, StringManipResultsView):
        _translate = QtCore.QCoreApplication.translate
        StringManipResultsView.setWindowTitle(_translate("StringManipResultsView", "Form"))
