# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\klacourse\Documents\NGosselin\gitRepos\ceamscarms\Stand_alone_apps\scinodes_poc\src\main\python\plugins\AmplitudeVarDetector\Ui_AmplitudeVarDetectorResultsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_AmplitudeVarDetectorResultsView(object):
    def setupUi(self, AmplitudeVarDetectorResultsView):
        AmplitudeVarDetectorResultsView.setObjectName("AmplitudeVarDetectorResultsView")
        AmplitudeVarDetectorResultsView.resize(677, 303)
        self.verticalLayout = QtWidgets.QVBoxLayout(AmplitudeVarDetectorResultsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.result_layout = QtWidgets.QVBoxLayout()
        self.result_layout.setObjectName("result_layout")
        self.verticalLayout.addLayout(self.result_layout)

        self.retranslateUi(AmplitudeVarDetectorResultsView)
        QtCore.QMetaObject.connectSlotsByName(AmplitudeVarDetectorResultsView)

    def retranslateUi(self, AmplitudeVarDetectorResultsView):
        _translate = QtCore.QCoreApplication.translate
        AmplitudeVarDetectorResultsView.setWindowTitle(_translate("AmplitudeVarDetectorResultsView", "Form"))
