# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\klacourse\Documents\NGosselin\gitRepos\ceamscarms\Stand_alone_apps\scinodes_poc\src\main\python\plugins\A4PreciseEvents\Ui_A4PreciseEventsResultsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_A4PreciseEventsResultsView(object):
    def setupUi(self, A4PreciseEventsResultsView):
        A4PreciseEventsResultsView.setObjectName("A4PreciseEventsResultsView")
        A4PreciseEventsResultsView.resize(483, 360)
        self.verticalLayout = QtWidgets.QVBoxLayout(A4PreciseEventsResultsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.result_layout = QtWidgets.QVBoxLayout()
        self.result_layout.setObjectName("result_layout")
        self.verticalLayout.addLayout(self.result_layout)

        self.retranslateUi(A4PreciseEventsResultsView)
        QtCore.QMetaObject.connectSlotsByName(A4PreciseEventsResultsView)

    def retranslateUi(self, A4PreciseEventsResultsView):
        _translate = QtCore.QCoreApplication.translate
        A4PreciseEventsResultsView.setWindowTitle(_translate("A4PreciseEventsResultsView", "Form"))
