# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\klacourse\Documents\NGosselin\gitRepos\ceamscarms\Stand_alone_apps\scinodes_poc\src\main\python\plugins\ScoringCompleteness\Ui_ScoringCompletenessSettingsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_ScoringCompletenessSettingsView(object):
    def setupUi(self, ScoringCompletenessSettingsView):
        ScoringCompletenessSettingsView.setObjectName("ScoringCompletenessSettingsView")
        ScoringCompletenessSettingsView.resize(425, 292)
        self.verticalLayout = QtWidgets.QVBoxLayout(ScoringCompletenessSettingsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.output_file_label = QtWidgets.QLabel(ScoringCompletenessSettingsView)
        self.output_file_label.setObjectName("output_file_label")
        self.horizontalLayout.addWidget(self.output_file_label)
        self.output_file_lineedit = QtWidgets.QLineEdit(ScoringCompletenessSettingsView)
        self.output_file_lineedit.setText("")
        self.output_file_lineedit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output_file_lineedit.setObjectName("output_file_lineedit")
        self.horizontalLayout.addWidget(self.output_file_lineedit)
        self.chosse_button = QtWidgets.QPushButton(ScoringCompletenessSettingsView)
        self.chosse_button.setObjectName("chosse_button")
        self.horizontalLayout.addWidget(self.chosse_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 240, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(ScoringCompletenessSettingsView)
        self.chosse_button.clicked.connect(ScoringCompletenessSettingsView.on_choose)
        QtCore.QMetaObject.connectSlotsByName(ScoringCompletenessSettingsView)

    def retranslateUi(self, ScoringCompletenessSettingsView):
        _translate = QtCore.QCoreApplication.translate
        ScoringCompletenessSettingsView.setWindowTitle(_translate("ScoringCompletenessSettingsView", "Form"))
        self.output_file_label.setText(_translate("ScoringCompletenessSettingsView", "Output file"))
        self.output_file_lineedit.setToolTip(_translate("ScoringCompletenessSettingsView", "Define the output file where the summary of the completeness of the scoring will be wrtiten. "))
        self.output_file_lineedit.setPlaceholderText(_translate("ScoringCompletenessSettingsView", "Define the output file."))
        self.chosse_button.setToolTip(_translate("ScoringCompletenessSettingsView", "Open the file explorer to choose the location and the name of the output file."))
        self.chosse_button.setText(_translate("ScoringCompletenessSettingsView", "Choose"))
