# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Dutil\Python\PycharmProjects\virtual_env\SYS818_venv\snooz-toolbox\src\main\python\plugins\TsvWriter\Ui_TsvWriterSettingsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_TsvWriterSettingsView(object):
    def setupUi(self, TsvWriterSettingsView):
        TsvWriterSettingsView.setObjectName("TsvWriterSettingsView")
        TsvWriterSettingsView.resize(411, 210)
        self.verticalLayout = QtWidgets.QVBoxLayout(TsvWriterSettingsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(TsvWriterSettingsView)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.filename_lineedit = QtWidgets.QLineEdit(TsvWriterSettingsView)
        self.filename_lineedit.setText("")
        self.filename_lineedit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.filename_lineedit.setObjectName("filename_lineedit")
        self.gridLayout.addWidget(self.filename_lineedit, 0, 1, 1, 1)
        self.choose_pushbutton = QtWidgets.QPushButton(TsvWriterSettingsView)
        self.choose_pushbutton.setObjectName("choose_pushbutton")
        self.gridLayout.addWidget(self.choose_pushbutton, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.EDF_annot_checkBox = QtWidgets.QCheckBox(TsvWriterSettingsView)
        self.EDF_annot_checkBox.setMinimumSize(QtCore.QSize(0, 0))
        self.EDF_annot_checkBox.setObjectName("EDF_annot_checkBox")
        self.verticalLayout.addWidget(self.EDF_annot_checkBox)
        self.add_time_checkBox = QtWidgets.QCheckBox(TsvWriterSettingsView)
        self.add_time_checkBox.setObjectName("add_time_checkBox")
        self.verticalLayout.addWidget(self.add_time_checkBox)
        self.append_data_checkBox = QtWidgets.QCheckBox(TsvWriterSettingsView)
        self.append_data_checkBox.setObjectName("append_data_checkBox")
        self.verticalLayout.addWidget(self.append_data_checkBox)
        self.index_checkBox = QtWidgets.QCheckBox(TsvWriterSettingsView)
        self.index_checkBox.setObjectName("index_checkBox")
        self.verticalLayout.addWidget(self.index_checkBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(TsvWriterSettingsView)
        self.choose_pushbutton.clicked.connect(TsvWriterSettingsView.on_choose)
        QtCore.QMetaObject.connectSlotsByName(TsvWriterSettingsView)

    def retranslateUi(self, TsvWriterSettingsView):
        _translate = QtCore.QCoreApplication.translate
        TsvWriterSettingsView.setWindowTitle(_translate("TsvWriterSettingsView", "Form"))
        self.label.setText(_translate("TsvWriterSettingsView", "Filename"))
        self.filename_lineedit.setPlaceholderText(_translate("TsvWriterSettingsView", "Choose a TSV file write to"))
        self.choose_pushbutton.setText(_translate("TsvWriterSettingsView", "Choose"))
        self.EDF_annot_checkBox.setToolTip(_translate("TsvWriterSettingsView", "To write specific channel event in the EDF+ format.\n"
"event_name = event_name@@channel_label ex) spindle@@EEG C3"))
        self.EDF_annot_checkBox.setText(_translate("TsvWriterSettingsView", "EDF+ annotations format"))
        self.add_time_checkBox.setText(_translate("TsvWriterSettingsView", "Add time elapsed (HH:MM:SS)"))
        self.append_data_checkBox.setText(_translate("TsvWriterSettingsView", "Append data to file"))
        self.index_checkBox.setText(_translate("TsvWriterSettingsView", "Add index values"))
