# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\klacourse\Documents\NGosselin\gitRepos\ceamscarms\Stand_alone_apps\snooz-toolbox\src\main\python\plugins\ScoringCompleteness\Ui_ScoringCompletenessResultsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_ScoringCompletenessResultsView(object):
    def setupUi(self, ScoringCompletenessResultsView):
        ScoringCompletenessResultsView.setObjectName("ScoringCompletenessResultsView")
        ScoringCompletenessResultsView.resize(483, 360)
        self.verticalLayout = QtWidgets.QVBoxLayout(ScoringCompletenessResultsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.result_layout = QtWidgets.QVBoxLayout()
        self.result_layout.setObjectName("result_layout")
        self.verticalLayout.addLayout(self.result_layout)

        self.retranslateUi(ScoringCompletenessResultsView)
        QtCore.QMetaObject.connectSlotsByName(ScoringCompletenessResultsView)

    def retranslateUi(self, ScoringCompletenessResultsView):
        _translate = QtCore.QCoreApplication.translate
        ScoringCompletenessResultsView.setWindowTitle(_translate("ScoringCompletenessResultsView", "Form"))
