# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\klacourse\Documents\NGosselin\gitRepos\ceamscarms\Stand_alone_apps\scinodes_poc\src\main\python\plugins\FilterSignal\Ui_FilterSignalResultsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_FilterSignalResultsView(object):
    def setupUi(self, FilterSignalResultsView):
        FilterSignalResultsView.setObjectName("FilterSignalResultsView")
        FilterSignalResultsView.resize(483, 360)
        self.verticalLayout = QtWidgets.QVBoxLayout(FilterSignalResultsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.result_layout = QtWidgets.QVBoxLayout()
        self.result_layout.setObjectName("result_layout")
        self.verticalLayout.addLayout(self.result_layout)

        self.retranslateUi(FilterSignalResultsView)
        QtCore.QMetaObject.connectSlotsByName(FilterSignalResultsView)

    def retranslateUi(self, FilterSignalResultsView):
        _translate = QtCore.QCoreApplication.translate
        FilterSignalResultsView.setWindowTitle(_translate("FilterSignalResultsView", "Form"))
