# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Ui_IntroStep.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import themes_rc

class Ui_IntroStep(object):
    def setupUi(self, IntroStep):
        if not IntroStep.objectName():
            IntroStep.setObjectName(u"IntroStep")
        IntroStep.resize(1018, 841)
        self.horizontalLayout = QHBoxLayout(IntroStep)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.textEdit = QTextEdit(IntroStep)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setFrameShape(QFrame.HLine)
        self.textEdit.setFrameShadow(QFrame.Plain)
        self.textEdit.setLineWidth(0)
        self.textEdit.setReadOnly(True)

        self.horizontalLayout.addWidget(self.textEdit)


        self.retranslateUi(IntroStep)

        QMetaObject.connectSlotsByName(IntroStep)
    # setupUi

    def retranslateUi(self, IntroStep):
        IntroStep.setWindowTitle("")
        IntroStep.setStyleSheet(QCoreApplication.translate("IntroStep", u"font: 12pt \"Roboto\";", None))
        self.textEdit.setHtml(QCoreApplication.translate("IntroStep", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Roboto'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Power Spectral Analysis (PSA) Cohort Review</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent"
                        ":0; text-indent:0px;\"><span style=\" font-size:12pt;\">A tool to explore, clean (remove bad channels and rename channels) and transpose the PSA file in order to have 1 subject per row.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; text-decoration: underline;\">1 - Input Files :</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">PSA File : </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">	Add your PSA files generated by the tool Power Spectral Analysis (PSA).</span></p>\n"
"<p style="
                        "\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">	You can append more than one PSA file. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Channel label : </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"docs-internal-guid-063424ec-7fff-f025-1e92-4c2d89e8c6df\"></a><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">	</span><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">The channel label is editable by double-clicking on the name.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Arial'; font-"
                        "size:12pt; color:#000000; background-color:transparent;\">	You can change the channel name at the subject level or at the cohort level.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%;\"><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">	A channel label changed at the cohort level will be effective to all the subjects loaded.<br />	</span><a name=\"docs-internal-guid-f4d620f5-7fff-c293-f18e-2502f4c333fa\"></a><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">U</span><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">ncheck a channel to remove it.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%;\"><a name=\"docs-internal-guid-dddb6927-7fff-085b-95eb-f8ee0decd42b\"><"
                        "/a><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">R</span><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">egion Of Interest : </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%;\"><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">	You can add ROI at the cohort level to average many channels together.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%;\"><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">	Once you press the &quot;Add ROI&quot; button : check the channels to include in the ROI (this list will be adapted to the cohort loaded).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px"
                        "; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%;\"><a name=\"docs-internal-guid-845123fe-7fff-4892-4560-2e53be980bae\"></a><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">	</span><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">Check the blank option if you want the ROI empty (blank) when data is missing for the mean otherwise missing data is just ignored.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; text-decoration: underline;\">2 - Frequency Band :</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">	</span><a name=\"docs-internal-guid-c9ccd9e0-7fff-5041-9169-1d6acf3f13b1\"></a><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; backg"
                        "round-color:transparent;\">Y</span><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">ou can add a new band with the button \u201cAdd\u201d or load an existing file with the button \u201cLoad\u201d.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">	You can edit a frequency band loaded.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'Arial'; font-size:12pt; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"docs-internal-guid-1c4e15c1-7fff-9c81-cd60-36c8b6e122a0\"></a><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color"
                        ":transparent;\">	</span><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">The spectral power can be absolute or relative.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">	- For absolute power : init only the numerator of the frequency band.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">	\u201cnum-start(Hz)\u201d and \u201cnum-end(Hz)\u201d must be init and \u201cden-start(Hz)\u201d and \u201cden-end(Hz)\u201d should be let nan (not a number) </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-bloc"
                        "k-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:'Arial'; font-size:12pt; font-weight:696; color:#000000; background-color:transparent;\">	</span><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">- For relative power : init the numerator and the denominator of the frequency band.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">	</span><a name=\"docs-internal-guid-93546a18-7fff-7afd-4765-1f4686eca915\"></a><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">Y</span><span style=\" font-family:'Arial'; font-size:12pt; color:#000000; background-color:transparent;\">ou can save the frequency band you edited.</span></p>\n"
"<p style=\""
                        "-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; text-decoration: underline;\">3 - Output File :</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">	Check the file you want to generate: the PSA file cleaned (with edited channels) and/or the transposed PSA file. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">	"
                        "If you want to export the transposed PSA file, define how to average the spectral power across the recording.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">	-Select &quot;Total&quot; to output the average through the whole recording.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">	-Select &quot;Distribution per hour&quot; to output the average per real clock hour, from hour 1 to 12.  The start point is the sleep onset.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">	-Select &quot;Distribution per sleep cycle&quot; to output the average per sleep cycle, from sleep cycle 1 to 6.  The start point is the sleep onset.</span></p>\n"
"<p style=\" margin-top"
                        ":0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">	-Select &quot;Distribution per annotation&quot; to output the average per selected annotation. No cycle or hour information is available for this option.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">	Define the filename to save the exported files (the sufix _clean or _transposed will be added to the filename)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">	The output file is a .tsv (tab separated values) file. </span></p>\n"
"<p style=\" margin-top:0px; margin-bott"
                        "om:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">	Warning : the current output is added (appended) to the existing output file.</span></p></body></html>", None))
    # retranslateUi

