# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\klacourse\Documents\NGosselin\gitRepos\ceamscarms\Stand_alone_apps\scinodes_poc\src\main\python\plugins\ResetSignalArtefact\Ui_ResetSignalArtefactResultsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_ResetSignalArtefactResultsView(object):
    def setupUi(self, ResetSignalArtefactResultsView):
        ResetSignalArtefactResultsView.setObjectName("ResetSignalArtefactResultsView")
        ResetSignalArtefactResultsView.resize(483, 360)
        self.verticalLayout = QtWidgets.QVBoxLayout(ResetSignalArtefactResultsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.result_layout = QtWidgets.QVBoxLayout()
        self.result_layout.setObjectName("result_layout")
        self.verticalLayout.addLayout(self.result_layout)

        self.retranslateUi(ResetSignalArtefactResultsView)
        QtCore.QMetaObject.connectSlotsByName(ResetSignalArtefactResultsView)

    def retranslateUi(self, ResetSignalArtefactResultsView):
        _translate = QtCore.QCoreApplication.translate
        ResetSignalArtefactResultsView.setWindowTitle(_translate("ResetSignalArtefactResultsView", "Form"))
