# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Dutil\Python\PycharmProjects\virtual_env\SYS818_venv\scinodes_poc\src\main\python\plugins\SignalsFromEvents\Ui_SignalsFromEventsSettingsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_SignalsFromEventsSettingsView(object):
    def setupUi(self, SignalsFromEventsSettingsView):
        SignalsFromEventsSettingsView.setObjectName("SignalsFromEventsSettingsView")
        SignalsFromEventsSettingsView.resize(272, 137)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(SignalsFromEventsSettingsView)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(SignalsFromEventsSettingsView)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(SignalsFromEventsSettingsView)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.events_names_lineEdit = QtWidgets.QLineEdit(SignalsFromEventsSettingsView)
        self.events_names_lineEdit.setObjectName("events_names_lineEdit")
        self.horizontalLayout.addWidget(self.events_names_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)

        self.retranslateUi(SignalsFromEventsSettingsView)
        QtCore.QMetaObject.connectSlotsByName(SignalsFromEventsSettingsView)

    def retranslateUi(self, SignalsFromEventsSettingsView):
        _translate = QtCore.QCoreApplication.translate
        SignalsFromEventsSettingsView.setWindowTitle(_translate("SignalsFromEventsSettingsView", "Form"))
        self.label_8.setText(_translate("SignalsFromEventsSettingsView", "SignalsFromEvents settings"))
        self.label.setText(_translate("SignalsFromEventsSettingsView", "Event name"))
        self.events_names_lineEdit.setToolTip(_translate("SignalsFromEventsSettingsView", "String of the desired events to take in account. Separated by a comma without spaces. An empty string will take every events in the dataframe."))
