# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\klacourse\Documents\NGosselin\gitRepos\ceamscarms\Stand_alone_apps\scinodes_poc\src\main\python\plugins\Stft\Ui_StftResultsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_StftResultsView(object):
    def setupUi(self, StftResultsView):
        StftResultsView.setObjectName("StftResultsView")
        StftResultsView.resize(668, 105)
        self.gridLayout = QtWidgets.QGridLayout(StftResultsView)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.time_label = QtWidgets.QLabel(StftResultsView)
        self.time_label.setObjectName("time_label")
        self.horizontalLayout.addWidget(self.time_label)
        self.time_lineEdit = QtWidgets.QLineEdit(StftResultsView)
        self.time_lineEdit.setObjectName("time_lineEdit")
        self.horizontalLayout.addWidget(self.time_lineEdit)
        self.previous_pb = QtWidgets.QPushButton(StftResultsView)
        self.previous_pb.setObjectName("previous_pb")
        self.horizontalLayout.addWidget(self.previous_pb)
        self.next_pb = QtWidgets.QPushButton(StftResultsView)
        self.next_pb.setObjectName("next_pb")
        self.horizontalLayout.addWidget(self.next_pb)
        self.length_label = QtWidgets.QLabel(StftResultsView)
        self.length_label.setObjectName("length_label")
        self.horizontalLayout.addWidget(self.length_label)
        self.length_lineEdit = QtWidgets.QLineEdit(StftResultsView)
        self.length_lineEdit.setObjectName("length_lineEdit")
        self.horizontalLayout.addWidget(self.length_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.log_cb = QtWidgets.QCheckBox(StftResultsView)
        self.log_cb.setCheckable(True)
        self.log_cb.setChecked(True)
        self.log_cb.setTristate(False)
        self.log_cb.setObjectName("log_cb")
        self.horizontalLayout_2.addWidget(self.log_cb)
        self.zoom_cb = QtWidgets.QCheckBox(StftResultsView)
        self.zoom_cb.setChecked(True)
        self.zoom_cb.setObjectName("zoom_cb")
        self.horizontalLayout_2.addWidget(self.zoom_cb)
        spacerItem = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.file_label = QtWidgets.QLabel(StftResultsView)
        self.file_label.setObjectName("file_label")
        self.horizontalLayout_2.addWidget(self.file_label)
        self.filename_lineEdit = QtWidgets.QLineEdit(StftResultsView)
        self.filename_lineEdit.setObjectName("filename_lineEdit")
        self.horizontalLayout_2.addWidget(self.filename_lineEdit)
        self.choose_pb = QtWidgets.QPushButton(StftResultsView)
        self.choose_pb.setObjectName("choose_pb")
        self.horizontalLayout_2.addWidget(self.choose_pb)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.result_layout = QtWidgets.QVBoxLayout()
        self.result_layout.setObjectName("result_layout")
        self.verticalLayout.addLayout(self.result_layout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(StftResultsView)
        self.choose_pb.clicked.connect(StftResultsView.on_choose)
        self.next_pb.clicked.connect(StftResultsView.on_next)
        self.previous_pb.clicked.connect(StftResultsView.on_previous)
        self.time_lineEdit.returnPressed.connect(StftResultsView.on_time_changed)
        self.length_lineEdit.returnPressed.connect(StftResultsView.on_time_changed)
        self.zoom_cb.stateChanged['int'].connect(StftResultsView.on_plot_cb)
        self.log_cb.stateChanged['int'].connect(StftResultsView.on_plot_cb)
        QtCore.QMetaObject.connectSlotsByName(StftResultsView)

    def retranslateUi(self, StftResultsView):
        _translate = QtCore.QCoreApplication.translate
        StftResultsView.setWindowTitle(_translate("StftResultsView", "Form"))
        self.time_label.setText(_translate("StftResultsView", "Time elapsed (HH:MM:SS)"))
        self.time_lineEdit.setText(_translate("StftResultsView", "00:00:00"))
        self.previous_pb.setText(_translate("StftResultsView", "<<"))
        self.next_pb.setText(_translate("StftResultsView", ">>"))
        self.length_label.setText(_translate("StftResultsView", "Window length"))
        self.length_lineEdit.setText(_translate("StftResultsView", "30"))
        self.log_cb.setText(_translate("StftResultsView", "Show log scale"))
        self.zoom_cb.setText(_translate("StftResultsView", "Show <30 Hz"))
        self.file_label.setText(_translate("StftResultsView", "To load another STFT file"))
        self.filename_lineEdit.setText(_translate("StftResultsView", "filename"))
        self.choose_pb.setText(_translate("StftResultsView", "Choose"))
