# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/david/projects/snooz-toolbox/src/main/python/plugins/EventTemporalLink/Ui_EventTemporalLinkSettingsView.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from qtpy import QtCore, QtGui, QtWidgets


class Ui_EventTemporalLinkSettingsView(object):
    def setupUi(self, EventTemporalLinkSettingsView):
        EventTemporalLinkSettingsView.setObjectName("EventTemporalLinkSettingsView")
        EventTemporalLinkSettingsView.resize(711, 333)
        self.verticalLayout = QtWidgets.QVBoxLayout(EventTemporalLinkSettingsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.event_reports_horizontalLayout = QtWidgets.QHBoxLayout()
        self.event_reports_horizontalLayout.setObjectName("event_reports_horizontalLayout")
        self.event_reports_label = QtWidgets.QLabel(EventTemporalLinkSettingsView)
        self.event_reports_label.setObjectName("event_reports_label")
        self.event_reports_horizontalLayout.addWidget(self.event_reports_label)
        self.event_reports_lineedit = QtWidgets.QLineEdit(EventTemporalLinkSettingsView)
        self.event_reports_lineedit.setObjectName("event_reports_lineedit")
        self.event_reports_horizontalLayout.addWidget(self.event_reports_lineedit)
        self.verticalLayout.addLayout(self.event_reports_horizontalLayout)
        self.record_info_horizontalLayout = QtWidgets.QHBoxLayout()
        self.record_info_horizontalLayout.setObjectName("record_info_horizontalLayout")
        self.record_info_label = QtWidgets.QLabel(EventTemporalLinkSettingsView)
        self.record_info_label.setObjectName("record_info_label")
        self.record_info_horizontalLayout.addWidget(self.record_info_label)
        self.record_info_lineedit = QtWidgets.QLineEdit(EventTemporalLinkSettingsView)
        self.record_info_lineedit.setObjectName("record_info_lineedit")
        self.record_info_horizontalLayout.addWidget(self.record_info_lineedit)
        self.verticalLayout.addLayout(self.record_info_horizontalLayout)
        self.window_size_horizontalLayout = QtWidgets.QHBoxLayout()
        self.window_size_horizontalLayout.setObjectName("window_size_horizontalLayout")
        self.window_size_label = QtWidgets.QLabel(EventTemporalLinkSettingsView)
        self.window_size_label.setObjectName("window_size_label")
        self.window_size_horizontalLayout.addWidget(self.window_size_label)
        self.window_size_lineedit = QtWidgets.QLineEdit(EventTemporalLinkSettingsView)
        self.window_size_lineedit.setObjectName("window_size_lineedit")
        self.window_size_horizontalLayout.addWidget(self.window_size_lineedit)
        self.verticalLayout.addLayout(self.window_size_horizontalLayout)
        self.temporal_links_horizontalLayout = QtWidgets.QHBoxLayout()
        self.temporal_links_horizontalLayout.setObjectName("temporal_links_horizontalLayout")
        self.temporal_links_label = QtWidgets.QLabel(EventTemporalLinkSettingsView)
        self.temporal_links_label.setObjectName("temporal_links_label")
        self.temporal_links_horizontalLayout.addWidget(self.temporal_links_label)
        self.temporal_links_lineedit = QtWidgets.QLineEdit(EventTemporalLinkSettingsView)
        self.temporal_links_lineedit.setObjectName("temporal_links_lineedit")
        self.temporal_links_horizontalLayout.addWidget(self.temporal_links_lineedit)
        self.verticalLayout.addLayout(self.temporal_links_horizontalLayout)
        self.html_report_horizontalLayout = QtWidgets.QHBoxLayout()
        self.html_report_horizontalLayout.setObjectName("html_report_horizontalLayout")
        self.html_report_label = QtWidgets.QLabel(EventTemporalLinkSettingsView)
        self.html_report_label.setObjectName("html_report_label")
        self.html_report_horizontalLayout.addWidget(self.html_report_label)
        self.html_report_lineedit = QtWidgets.QLineEdit(EventTemporalLinkSettingsView)
        self.html_report_lineedit.setObjectName("html_report_lineedit")
        self.html_report_horizontalLayout.addWidget(self.html_report_lineedit)
        self.verticalLayout.addLayout(self.html_report_horizontalLayout)
        self.html_report_config_horizontalLayout = QtWidgets.QHBoxLayout()
        self.html_report_config_horizontalLayout.setObjectName("html_report_config_horizontalLayout")
        self.html_report_config_label = QtWidgets.QLabel(EventTemporalLinkSettingsView)
        self.html_report_config_label.setObjectName("html_report_config_label")
        self.html_report_config_horizontalLayout.addWidget(self.html_report_config_label)
        self.html_report_config_lineedit = QtWidgets.QLineEdit(EventTemporalLinkSettingsView)
        self.html_report_config_lineedit.setObjectName("html_report_config_lineedit")
        self.html_report_config_horizontalLayout.addWidget(self.html_report_config_lineedit)
        self.verticalLayout.addLayout(self.html_report_config_horizontalLayout)
        self.csv_report_horizontalLayout = QtWidgets.QHBoxLayout()
        self.csv_report_horizontalLayout.setObjectName("csv_report_horizontalLayout")
        self.csv_report_label = QtWidgets.QLabel(EventTemporalLinkSettingsView)
        self.csv_report_label.setObjectName("csv_report_label")
        self.csv_report_horizontalLayout.addWidget(self.csv_report_label)
        self.csv_report_lineedit = QtWidgets.QLineEdit(EventTemporalLinkSettingsView)
        self.csv_report_lineedit.setObjectName("csv_report_lineedit")
        self.csv_report_horizontalLayout.addWidget(self.csv_report_lineedit)
        self.verticalLayout.addLayout(self.csv_report_horizontalLayout)
        self.base_output_fullpath_horizontalLayout = QtWidgets.QHBoxLayout()
        self.base_output_fullpath_horizontalLayout.setObjectName("base_output_fullpath_horizontalLayout")
        self.base_output_fullpath_label = QtWidgets.QLabel(EventTemporalLinkSettingsView)
        self.base_output_fullpath_label.setObjectName("base_output_fullpath_label")
        self.base_output_fullpath_horizontalLayout.addWidget(self.base_output_fullpath_label)
        self.base_output_fullpath_lineedit = QtWidgets.QLineEdit(EventTemporalLinkSettingsView)
        self.base_output_fullpath_lineedit.setObjectName("base_output_fullpath_lineedit")
        self.base_output_fullpath_horizontalLayout.addWidget(self.base_output_fullpath_lineedit)
        self.verticalLayout.addLayout(self.base_output_fullpath_horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(EventTemporalLinkSettingsView)
        QtCore.QMetaObject.connectSlotsByName(EventTemporalLinkSettingsView)

    def retranslateUi(self, EventTemporalLinkSettingsView):
        _translate = QtCore.QCoreApplication.translate
        EventTemporalLinkSettingsView.setWindowTitle(_translate("EventTemporalLinkSettingsView", "Form"))
        self.event_reports_label.setText(_translate("EventTemporalLinkSettingsView", "event_reports"))
        self.record_info_label.setText(_translate("EventTemporalLinkSettingsView", "record_info"))
        self.window_size_label.setText(_translate("EventTemporalLinkSettingsView", "window_size"))
        self.temporal_links_label.setText(_translate("EventTemporalLinkSettingsView", "temporal_links"))
        self.html_report_label.setText(_translate("EventTemporalLinkSettingsView", "html_report"))
        self.html_report_config_label.setText(_translate("EventTemporalLinkSettingsView", "html_report_config"))
        self.csv_report_label.setText(_translate("EventTemporalLinkSettingsView", "csv_report"))
        self.base_output_fullpath_label.setText(_translate("EventTemporalLinkSettingsView", "base_output_fullpath"))
