# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\klacourse\Documents\NGosselin\gitRepos\ceamscarms\Stand_alone_apps\scinodes_poc\src\main\python\plugins\ThresholdComputation\Ui_ThresholdComputationResultsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_ThresholdComputationResultsView(object):
    def setupUi(self, ThresholdComputationResultsView):
        ThresholdComputationResultsView.setObjectName("ThresholdComputationResultsView")
        ThresholdComputationResultsView.resize(483, 360)
        self.verticalLayout = QtWidgets.QVBoxLayout(ThresholdComputationResultsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.result_layout = QtWidgets.QVBoxLayout()
        self.result_layout.setObjectName("result_layout")
        self.verticalLayout.addLayout(self.result_layout)

        self.retranslateUi(ThresholdComputationResultsView)
        QtCore.QMetaObject.connectSlotsByName(ThresholdComputationResultsView)

    def retranslateUi(self, ThresholdComputationResultsView):
        _translate = QtCore.QCoreApplication.translate
        ThresholdComputationResultsView.setWindowTitle(_translate("ThresholdComputationResultsView", "Form"))
