# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\klacourse\Documents\NGosselin\gitRepos\ceamscarms\Stand_alone_apps\snooz-toolbox\src\main\python\plugins\EventCompare\Ui_EventCompareResultsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_EventCompareResultsView(object):
    def setupUi(self, EventCompareResultsView):
        EventCompareResultsView.setObjectName("EventCompareResultsView")
        EventCompareResultsView.resize(660, 550)
        self.verticalLayout = QtWidgets.QVBoxLayout(EventCompareResultsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.result_tablewidget = QtWidgets.QTableWidget(EventCompareResultsView)
        self.result_tablewidget.setObjectName("result_tablewidget")
        self.result_tablewidget.setColumnCount(0)
        self.result_tablewidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.result_tablewidget)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(EventCompareResultsView)
        QtCore.QMetaObject.connectSlotsByName(EventCompareResultsView)

    def retranslateUi(self, EventCompareResultsView):
        _translate = QtCore.QCoreApplication.translate
        EventCompareResultsView.setWindowTitle(_translate("EventCompareResultsView", "Form"))
