# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\klacourse\Documents\NGosselin\gitRepos\ceamscarms\Stand_alone_apps\scinodes_poc\src\main\python\plugins\DiscardEvents\Ui_DiscardEventsResultsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_DiscardEventsResultsView(object):
    def setupUi(self, DiscardEventsResultsView):
        DiscardEventsResultsView.setObjectName("DiscardEventsResultsView")
        DiscardEventsResultsView.resize(483, 360)
        self.verticalLayout = QtWidgets.QVBoxLayout(DiscardEventsResultsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.result_layout = QtWidgets.QVBoxLayout()
        self.result_layout.setObjectName("result_layout")
        self.verticalLayout.addLayout(self.result_layout)

        self.retranslateUi(DiscardEventsResultsView)
        QtCore.QMetaObject.connectSlotsByName(DiscardEventsResultsView)

    def retranslateUi(self, DiscardEventsResultsView):
        _translate = QtCore.QCoreApplication.translate
        DiscardEventsResultsView.setWindowTitle(_translate("DiscardEventsResultsView", "Form"))
