# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\klacourse\Documents\NGosselin\gitRepos\ceamscarms\Stand_alone_apps\snooz-toolbox\src\main\python\plugins\DiscardEvents\Ui_DiscardEventsSettingsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_DiscardEventsSettingsView(object):
    def setupUi(self, DiscardEventsSettingsView):
        DiscardEventsSettingsView.setObjectName("DiscardEventsSettingsView")
        DiscardEventsSettingsView.resize(625, 417)
        self.verticalLayout = QtWidgets.QVBoxLayout(DiscardEventsSettingsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(DiscardEventsSettingsView)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.event_group_lineEdit = QtWidgets.QLineEdit(DiscardEventsSettingsView)
        self.event_group_lineEdit.setObjectName("event_group_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.event_group_lineEdit)
        self.label_2 = QtWidgets.QLabel(DiscardEventsSettingsView)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.event_name_lineEdit = QtWidgets.QLineEdit(DiscardEventsSettingsView)
        self.event_name_lineEdit.setObjectName("event_name_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.event_name_lineEdit)
        self.min_len_sec_label = QtWidgets.QLabel(DiscardEventsSettingsView)
        self.min_len_sec_label.setMinimumSize(QtCore.QSize(180, 0))
        self.min_len_sec_label.setMaximumSize(QtCore.QSize(180, 16777215))
        self.min_len_sec_label.setObjectName("min_len_sec_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.min_len_sec_label)
        self.min_len_sec_lineedit = QtWidgets.QLineEdit(DiscardEventsSettingsView)
        self.min_len_sec_lineedit.setObjectName("min_len_sec_lineedit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.min_len_sec_lineedit)
        self.max_len_sec_label = QtWidgets.QLabel(DiscardEventsSettingsView)
        self.max_len_sec_label.setMinimumSize(QtCore.QSize(180, 0))
        self.max_len_sec_label.setMaximumSize(QtCore.QSize(180, 16777215))
        self.max_len_sec_label.setObjectName("max_len_sec_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.max_len_sec_label)
        self.max_len_sec_lineedit = QtWidgets.QLineEdit(DiscardEventsSettingsView)
        self.max_len_sec_lineedit.setObjectName("max_len_sec_lineedit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.max_len_sec_lineedit)
        self.artefact_free_checkBox = QtWidgets.QCheckBox(DiscardEventsSettingsView)
        self.artefact_free_checkBox.setMinimumSize(QtCore.QSize(180, 0))
        self.artefact_free_checkBox.setMaximumSize(QtCore.QSize(180, 16777215))
        self.artefact_free_checkBox.setObjectName("artefact_free_checkBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.artefact_free_checkBox)
        self.artefact_group_label = QtWidgets.QLabel(DiscardEventsSettingsView)
        self.artefact_group_label.setMinimumSize(QtCore.QSize(180, 0))
        self.artefact_group_label.setMaximumSize(QtCore.QSize(180, 16777215))
        self.artefact_group_label.setObjectName("artefact_group_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.artefact_group_label)
        self.artefact_group_lineedit = QtWidgets.QLineEdit(DiscardEventsSettingsView)
        self.artefact_group_lineedit.setEnabled(False)
        self.artefact_group_lineedit.setObjectName("artefact_group_lineedit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.artefact_group_lineedit)
        self.artefact_name_label = QtWidgets.QLabel(DiscardEventsSettingsView)
        self.artefact_name_label.setMinimumSize(QtCore.QSize(180, 0))
        self.artefact_name_label.setMaximumSize(QtCore.QSize(180, 16777215))
        self.artefact_name_label.setObjectName("artefact_name_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.artefact_name_label)
        self.artefact_name_lineedit = QtWidgets.QLineEdit(DiscardEventsSettingsView)
        self.artefact_name_lineedit.setEnabled(False)
        self.artefact_name_lineedit.setObjectName("artefact_name_lineedit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.artefact_name_lineedit)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 193, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(DiscardEventsSettingsView)
        self.artefact_free_checkBox.clicked.connect(DiscardEventsSettingsView.on_artefact_free_check)
        QtCore.QMetaObject.connectSlotsByName(DiscardEventsSettingsView)

    def retranslateUi(self, DiscardEventsSettingsView):
        _translate = QtCore.QCoreApplication.translate
        DiscardEventsSettingsView.setWindowTitle(_translate("DiscardEventsSettingsView", "Form"))
        self.label.setText(_translate("DiscardEventsSettingsView", "Event group"))
        self.event_group_lineEdit.setToolTip(_translate("DiscardEventsSettingsView", "The user can define a single group (and let the name blank) or a single name (and let the group blank). \n"
"If group and name are defined, they must be defined in pairs.\n"
"Each group should be separated by a comma.\n"
"The group works as a pattern matching.  "))
        self.label_2.setText(_translate("DiscardEventsSettingsView", "Event name"))
        self.event_name_lineEdit.setToolTip(_translate("DiscardEventsSettingsView", "The user can define a single group (and let the name blank) or a single name (and let the group blank). \n"
"If group and name are defined, they must be defined in pairs.\n"
"Each name should be separated by a comma.\n"
"The name works as a pattern matching.  "))
        self.min_len_sec_label.setText(_translate("DiscardEventsSettingsView", "minimum length accepted (s)"))
        self.max_len_sec_label.setText(_translate("DiscardEventsSettingsView", "maximum length accepted (s)"))
        self.artefact_free_checkBox.setToolTip(_translate("DiscardEventsSettingsView", "Check to discard events that occur during an artefact."))
        self.artefact_free_checkBox.setText(_translate("DiscardEventsSettingsView", "artefact free"))
        self.artefact_group_label.setText(_translate("DiscardEventsSettingsView", "artefact group"))
        self.artefact_group_lineedit.setToolTip(_translate("DiscardEventsSettingsView", "The user can define a single group (and let the name blank) or a single name (and let the group blank). \n"
"If group and name are defined, they must be defined in pairs.\n"
"Each group should be separated by a comma.\n"
"The group works as a pattern matching.  "))
        self.artefact_name_label.setText(_translate("DiscardEventsSettingsView", "artefact name"))
        self.artefact_name_lineedit.setToolTip(_translate("DiscardEventsSettingsView", "The user can define a single group (and let the name blank) or a single name (and let the group blank). \n"
"If group and name are defined, they must be defined in pairs.\n"
"Each name should be separated by a comma.\n"
"The name works as a pattern matching.  "))
