# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\klacourse\Documents\NGosselin\gitRepos\ceamscarms\Stand_alone_apps\scinodes_poc\src\main\python\plugins\SleepStageRename\Ui_SleepStageRenameResultsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_SleepStageRenameResultsView(object):
    def setupUi(self, SleepStageRenameResultsView):
        SleepStageRenameResultsView.setObjectName("SleepStageRenameResultsView")
        SleepStageRenameResultsView.resize(927, 262)
        self.verticalLayout = QtWidgets.QVBoxLayout(SleepStageRenameResultsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.signal_layout = QtWidgets.QVBoxLayout()
        self.signal_layout.setObjectName("signal_layout")
        self.verticalLayout.addLayout(self.signal_layout)

        self.retranslateUi(SleepStageRenameResultsView)
        QtCore.QMetaObject.connectSlotsByName(SleepStageRenameResultsView)

    def retranslateUi(self, SleepStageRenameResultsView):
        _translate = QtCore.QCoreApplication.translate
        SleepStageRenameResultsView.setWindowTitle(_translate("SleepStageRenameResultsView", "Form"))
