# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\sampo\Python\PycharmProjects\scinode\snooz-toolbox\src\main\python\plugins\PerformanceByEvent\Ui_PerformanceByEventResultsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_PerformanceByEventResultsView(object):
    def setupUi(self, PerformanceByEventResultsView):
        PerformanceByEventResultsView.setObjectName("PerformanceByEventResultsView")
        PerformanceByEventResultsView.resize(660, 550)
        self.verticalLayout = QtWidgets.QVBoxLayout(PerformanceByEventResultsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.result_tablewidget = QtWidgets.QTableWidget(PerformanceByEventResultsView)
        self.result_tablewidget.setObjectName("result_tablewidget")
        self.result_tablewidget.setColumnCount(0)
        self.result_tablewidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.result_tablewidget)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(PerformanceByEventResultsView)
        QtCore.QMetaObject.connectSlotsByName(PerformanceByEventResultsView)

    def retranslateUi(self, PerformanceByEventResultsView):
        _translate = QtCore.QCoreApplication.translate
        PerformanceByEventResultsView.setWindowTitle(_translate("PerformanceByEventResultsView", "Form"))
