# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\klacourse\Documents\NGosselin\gitRepos\ceamscarms\Stand_alone_apps\scinodes_poc\src\main\python\plugins\EdfXmlWriter\Ui_EdfXmlWriterSettingsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_EdfXmlWriterSettingsView(object):
    def setupUi(self, EdfXmlWriterSettingsView):
        EdfXmlWriterSettingsView.setObjectName("EdfXmlWriterSettingsView")
        EdfXmlWriterSettingsView.resize(711, 333)
        self.verticalLayout = QtWidgets.QVBoxLayout(EdfXmlWriterSettingsView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filename_horizontalLayout = QtWidgets.QHBoxLayout()
        self.filename_horizontalLayout.setObjectName("filename_horizontalLayout")
        self.filename_label = QtWidgets.QLabel(EdfXmlWriterSettingsView)
        self.filename_label.setObjectName("filename_label")
        self.filename_horizontalLayout.addWidget(self.filename_label)
        self.filename_lineedit = QtWidgets.QLineEdit(EdfXmlWriterSettingsView)
        self.filename_lineedit.setObjectName("filename_lineedit")
        self.filename_horizontalLayout.addWidget(self.filename_lineedit)
        self.verticalLayout.addLayout(self.filename_horizontalLayout)
        self.events_horizontalLayout = QtWidgets.QHBoxLayout()
        self.events_horizontalLayout.setObjectName("events_horizontalLayout")
        self.events_label = QtWidgets.QLabel(EdfXmlWriterSettingsView)
        self.events_label.setObjectName("events_label")
        self.events_horizontalLayout.addWidget(self.events_label)
        self.events_lineedit = QtWidgets.QLineEdit(EdfXmlWriterSettingsView)
        self.events_lineedit.setObjectName("events_lineedit")
        self.events_horizontalLayout.addWidget(self.events_lineedit)
        self.verticalLayout.addLayout(self.events_horizontalLayout)
        self.epoch_len_horizontalLayout = QtWidgets.QHBoxLayout()
        self.epoch_len_horizontalLayout.setObjectName("epoch_len_horizontalLayout")
        self.epoch_len_label = QtWidgets.QLabel(EdfXmlWriterSettingsView)
        self.epoch_len_label.setObjectName("epoch_len_label")
        self.epoch_len_horizontalLayout.addWidget(self.epoch_len_label)
        self.epoch_len_lineedit = QtWidgets.QLineEdit(EdfXmlWriterSettingsView)
        self.epoch_len_lineedit.setObjectName("epoch_len_lineedit")
        self.epoch_len_horizontalLayout.addWidget(self.epoch_len_lineedit)
        self.verticalLayout.addLayout(self.epoch_len_horizontalLayout)
        self.stages_df_horizontalLayout = QtWidgets.QHBoxLayout()
        self.stages_df_horizontalLayout.setObjectName("stages_df_horizontalLayout")
        self.stages_df_label = QtWidgets.QLabel(EdfXmlWriterSettingsView)
        self.stages_df_label.setObjectName("stages_df_label")
        self.stages_df_horizontalLayout.addWidget(self.stages_df_label)
        self.stages_df_lineedit = QtWidgets.QLineEdit(EdfXmlWriterSettingsView)
        self.stages_df_lineedit.setObjectName("stages_df_lineedit")
        self.stages_df_horizontalLayout.addWidget(self.stages_df_lineedit)
        self.verticalLayout.addLayout(self.stages_df_horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(EdfXmlWriterSettingsView)
        QtCore.QMetaObject.connectSlotsByName(EdfXmlWriterSettingsView)

    def retranslateUi(self, EdfXmlWriterSettingsView):
        _translate = QtCore.QCoreApplication.translate
        EdfXmlWriterSettingsView.setWindowTitle(_translate("EdfXmlWriterSettingsView", "Form"))
        self.filename_label.setText(_translate("EdfXmlWriterSettingsView", "filename"))
        self.events_label.setText(_translate("EdfXmlWriterSettingsView", "events"))
        self.epoch_len_label.setText(_translate("EdfXmlWriterSettingsView", "epoch_len"))
        self.stages_df_label.setText(_translate("EdfXmlWriterSettingsView", "stages_df"))
